openapi: 3.0.0
info:
  title: Contacts API
  version: 1.0.0
servers:
  - url: http://localhost:3000

paths:
  /contacts:
    get:
      summary: Get all contacts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './components/schemas/Contact.yaml'
    post:
      summary: Add new contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/Contact.yaml'
      responses:
        '201':
          description: Contact created

  /contacts/{contactId}:
    parameters:
      - name: contactId
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get contact by ID
      responses:
        '200':
          description: Contact found
          content:
            application/json:
              schema:
                $ref: './components/schemas/Contact.yaml'
        '404':
          $ref: './components/responses/NotFound.yaml'
