openapi: 3.0.0
info:
  title: Contacts API
  version: 1.0.0
servers:
  - url: https://nodejs-hw-mongodb-1m6g.onrender.com/api-docs/

paths:
  /contacts:
    get:
      summary: Отримати всі контакти
      responses:
        '200':
          description: Успішна відповідь
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './components/schemas/Contact.yaml'  
    post:
      summary: Додати новий контакт
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/Contact.yaml'  
      responses:
        '201':
          description: Контакт створено

  /contacts/{contactId}:
    parameters:
      - name: contactId
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Отримати контакт за ID
      responses:
        '200':
          description: Контакт знайдено
          content:
            application/json:
              schema:
                $ref: './components/schemas/Contact.yaml'  
        '404':
          $ref: './components/responses/NotFound.yaml'  
    patch:
      summary: Оновити контакт за ID
      responses:
        '200':
          description: Контакт оновлено
          content:
            application/json:
              schema:
                $ref: './components/schemas/Contact.yaml'  
        '404':
          $ref: './components/responses/NotFound.yaml'  
    delete:
      summary: Видалити контакт за ID
      responses:
        '200':
          description: Контакт видалено
        '404':
          $ref: './components/responses/NotFound.yaml'  

components:
  schemas:
    Contact:
      $ref: './components/schemas/Contact.yaml'
  responses:
    NotFound:
      $ref: './components/responses/NotFound.yaml'
