openapi: 3.0.0
info:
  title: Contacts API
  version: 1.0.0
servers:
  - url: https://nodejs-hw-mongodb-1m6g.onrender.com/api-docs/

paths:
  /contacts:
    get:
      summary: Get all contacts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './components/schemas/Contact.yaml'  # Убедись, что этот путь правильный
    post:
      summary: Add new contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/Contact.yaml'  # Убедись, что этот путь правильный
      responses:
        '201':
          description: Contact created

  /contacts/{contactId}:
    parameters:
      - name: contactId
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get contact by ID
      responses:
        '200':
          description: Contact found
          content:
            application/json:
              schema:
                $ref: './components/schemas/Contact.yaml'  # Убедись, что этот путь правильный
        '404':
          $ref: './components/responses/NotFound.yaml'  # Убедись, что этот путь правильный
    patch:
      summary: Update contact by ID
      responses:
        '200':
          description: Contact updated
          content:
            application/json:
              schema:
                $ref: './components/schemas/Contact.yaml'  # Убедись, что этот путь правильный
        '404':
          $ref: './components/responses/NotFound.yaml'  # Убедись, что этот путь правильный
    delete:
      summary: Delete contact by ID
      responses:
        '200':
          description: Contact deleted
        '404':
          $ref: './components/responses/NotFound.yaml'  # Убедись, что этот путь правильный

components:
  schemas:
    Contact:
      $ref: './components/schemas/Contact.yaml'
  responses:
    NotFound:
      $ref: './components/responses/NotFound.yaml'
